spring:
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/securitydemo?useUnicode=true&characterEncoding=UTF-8&serverTimezone=UTC
    username: root
    password: 1234
  devtools:
    restart:
    #需要更新的目录
      additional-paths: resources/**,static/**,templates/**

logging:
  level:
    root: info
    com.lena: debug
  file: log/blog-dev.log

api-url:  /api

